
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int AND = 18;
  public static final int LT = 17;
  public static final int ELSE = 11;
  public static final int PLUS = 14;
  public static final int RBRACE = 7;
  public static final int RPAREN = 5;
  public static final int WHILE = 12;
  public static final int NOT = 19;
  public static final int IDENTIFIER = 22;
  public static final int IF = 10;
  public static final int LPAREN = 4;
  public static final int COLON = 9;
  public static final int LBRACE = 6;
  public static final int STRING_LITERAL = 21;
  public static final int INT_LITERAL = 20;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int DEF = 13;
  public static final int MINUS = 15;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "PRINT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "IF",
  "ELSE",
  "WHILE",
  "DEF",
  "PLUS",
  "MINUS",
  "TIMES",
  "LT",
  "AND",
  "NOT",
  "INT_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

