
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int RBRACK = 8;
  public static final int ELSE = 12;
  public static final int BOOL_LITERAL = 20;
  public static final int PLUS = 15;
  public static final int RBRACE = 6;
  public static final int RPAREN = 4;
  public static final int WHILE = 13;
  public static final int NOT = 18;
  public static final int LBRACK = 7;
  public static final int IDENTIFIER = 22;
  public static final int IF = 11;
  public static final int LPAREN = 3;
  public static final int COLON = 10;
  public static final int LBRACE = 5;
  public static final int STRING_LITERAL = 21;
  public static final int INT_LITERAL = 19;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int DEF = 14;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int NONE_LITERAL = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "COLON",
  "IF",
  "ELSE",
  "WHILE",
  "DEF",
  "PLUS",
  "MINUS",
  "TIMES",
  "NOT",
  "INT_LITERAL",
  "BOOL_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NONE_LITERAL"
  };
}

