package AST.Visitor;

import AST.*;
import src.syntaxtree.And;
import src.syntaxtree.ArrayAssign;
import src.syntaxtree.ArrayLength;
import src.syntaxtree.ArrayLookup;
import src.syntaxtree.Assign;
import src.syntaxtree.Block;
import src.syntaxtree.BooleanType;
import src.syntaxtree.Call;
import src.syntaxtree.ClassDeclExtends;
import src.syntaxtree.ClassDeclSimple;
import src.syntaxtree.Display;
import src.syntaxtree.False;
import src.syntaxtree.Formal;
import src.syntaxtree.Identifier;
import src.syntaxtree.IdentifierExp;
import src.syntaxtree.IdentifierType;
import src.syntaxtree.If;
import src.syntaxtree.IntArrayType;
import src.syntaxtree.IntegerLiteral;
import src.syntaxtree.IntegerType;
import src.syntaxtree.LessThan;
import src.syntaxtree.MainClass;
import src.syntaxtree.MethodDecl;
import src.syntaxtree.Minus;
import src.syntaxtree.NewArray;
import src.syntaxtree.NewObject;
import src.syntaxtree.Not;
import src.syntaxtree.Plus;
import src.syntaxtree.Print;
import src.syntaxtree.Program;
import src.syntaxtree.This;
import src.syntaxtree.Times;
import src.syntaxtree.True;
import src.syntaxtree.VarDecl;
import src.syntaxtree.While;

public interface Visitor {
  // Display added for toy example language.  Not used in MiniJava AST
  public void visit(Display n);
  public void visit(Program n);
  public void visit(MainClass n);
  public void visit(ClassDeclSimple n);
  public void visit(ClassDeclExtends n);
  public void visit(VarDecl n);
  public void visit(MethodDecl n);
  public void visit(Formal n);
  public void visit(IntArrayType n);
  public void visit(BooleanType n);
  public void visit(IntegerType n);
  public void visit(IdentifierType n);
  public void visit(Block n);
  public void visit(If n);
  public void visit(While n);
  public void visit(Print n);
  public void visit(Assign n);
  public void visit(ArrayAssign n);
  public void visit(And n);
  public void visit(LessThan n);
  public void visit(Plus n);
  public void visit(Minus n);
  public void visit(Times n);
  public void visit(ArrayLookup n);
  public void visit(ArrayLength n);
  public void visit(Call n);
  public void visit(IntegerLiteral n);
  public void visit(True n);
  public void visit(False n);
  public void visit(IdentifierExp n);
  public void visit(This n);
  public void visit(NewArray n);
  public void visit(NewObject n);
  public void visit(Not n);
  public void visit(Identifier n);
}
