package AST.Visitor;

import AST.And;
import AST.Assign;
import AST.Block;
import AST.BooleanLiteral;
import AST.BooleanType;
import AST.Call;
import AST.Defn;
import AST.Display;
import AST.Div;
import AST.Equals;
import AST.Formal;
import AST.GreaterEquals;
import AST.GreaterThan;
import AST.Identifier;
import AST.IdentifierExp;
import AST.IdentifierType;
import AST.If;
import AST.IntegerLiteral;
import AST.IntegerType;
import AST.LessEquals;
import AST.LessThan;
import AST.Minus;
import AST.Mod;
import AST.Not;
import AST.NotEquals;
import AST.Or;
import AST.Plus;
import AST.Print;
import AST.Program;
import AST.StringLiteral;
import AST.Times;
import AST.While;

public interface Visitor {
  // Display added for toy example language.  Not used in MiniJava AST
  public void visit(Display n);
  public void visit(Program n);
  public void visit(Defn n);
  public void visit(Formal n);
  public void visit(BooleanType n);
  public void visit(IntegerType n);
  public void visit(IdentifierType n);
  public void visit(Block n);
  public void visit(If n);
  public void visit(While n);
  public void visit(Print n);
  public void visit(Assign n);
  public void visit(And n);
  public void visit(Or n);
  public void visit(GreaterThan n);
  public void visit(LessThan n);
  public void visit(Equals n);
  public void visit(NotEquals n);
  public void visit(GreaterEquals n);
  public void visit(LessEquals n);
  public void visit(Plus n);
  public void visit(Minus n);
  public void visit(Times n);
  public void visit(Div n);
  public void visit(Mod n);
  public void visit(Call n);
  public void visit(IntegerLiteral n);
  public void visit(BooleanLiteral n);
  public void visit(StringLiteral n);
  public void visit(IdentifierExp n);
  public void visit(Not n);
  public void visit(Identifier n);
}
