
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 37;
  public static final int MULT = 23;
  public static final int LPAREN = 5;
  public static final int NONE_LITERAL = 39;
  public static final int MINUS = 22;
  public static final int RPAREN = 6;
  public static final int NOT = 34;
  public static final int SEMICOLON = 14;
  public static final int AND = 32;
  public static final int LT = 26;
  public static final int OR = 33;
  public static final int COMMA = 15;
  public static final int DIV = 24;
  public static final int GEQ = 29;
  public static final int PLUS = 21;
  public static final int ASSIGN = 2;
  public static final int IF = 17;
  public static final int DOT = 11;
  public static final int LEFT = 12;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int error = 1;
  public static final int MOD = 25;
  public static final int NEQ = 31;
  public static final int EQ = 30;
  public static final int LBRACK = 9;
  public static final int COLON = 16;
  public static final int LBRACE = 7;
  public static final int ELSE = 18;
  public static final int RBRACK = 10;
  public static final int WHILE = 19;
  public static final int RBRACE = 8;
  public static final int LEQ = 28;
  public static final int DEF = 20;
  public static final int RIGHT = 13;
  public static final int GT = 27;
  public static final int BOOL_LITERAL = 36;
  public static final int PRINT = 3;
  public static final int INT_LITERAL = 35;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "PRINT",
  "RETURN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "LEFT",
  "RIGHT",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "IF",
  "ELSE",
  "WHILE",
  "DEF",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "INT_LITERAL",
  "BOOL_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NONE_LITERAL"
  };
}

